[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
serde = "1.0"
sysinfo = "0.33.0"  # For process monitoring
toml = "0.8.19"  # For config management
system-tray = "0.6.0"  # For tray icon
tokio = { version = "1", features = ["full"] }  # For async runtime
eframe = "0.30.0" # For `egui` GUI
futures = "0.3"
glib = "0.20.7"
gio = "0.20.7"
tray-icon = "0.19.2"
image = "0.25.5"
iced = "0.13.1"
iced_native = "0.13.1"
web-sys = "0.3.67"